# general settings
name: SRCNN_SRx4_DIV2K_tinyDIV2K
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: ./data/DIV2K/GT
    dataroot_lq: ./data/DIV2K/LR
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 0
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: ./data/Set5/GT
    dataroot_lq: ./data/Set5/LR
    io_backend:
      type: disk

  # test:
  #   name: Set5
  #   type: PairedImageDataset
  #   dataroot_gt: ./data/Set5/GT
  #   dataroot_lq: ./data/Set5/LR
  #   io_backend:
  #     type: disk

# network structures
network_g:
  type: SRCNNNet
  channels: [3, 64, 32, 3]
  kernel_sizes: [9, 1, 5]
  upscale_factor: 4

# path
path:
  pretrain_network_g: ./basicsr_srcnn_x4k915_1x16_1000k_div2k_20200608-4186f232.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepRestartLR
    milestones: [500]
    gamma: 0.5

  total_iter: 1000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 100
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 100
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
